// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SantralOpsAPI.Persistence;

#nullable disable

namespace SantralOpsAPI.Migrations
{
  [DbContext(typeof(SantralOpsDbContext))]
  [Migration("20250731090119_InitialCreate")]
  partial class InitialCreate
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "9.0.7")
          .HasAnnotation("Relational:MaxIdentifierLength", 128);

      SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

      modelBuilder.Entity("SantralOpsAPI.Entities.Birim", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("Ad")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<DateTime>("CreatedDate")
                      .HasColumnType("datetime2");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("datetime2");

            b.HasKey("Id");

            b.ToTable("Birimler");
          });

      modelBuilder.Entity("SantralOpsAPI.Entities.Kargo", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("Aciklama")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<DateTime>("CreatedDate")
                      .HasColumnType("datetime2");

            b.Property<int>("Durum")
                      .HasColumnType("int");

            b.Property<string>("Gonderen")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("TakipNumarasi")
                      .HasColumnType("nvarchar(max)");

            b.Property<int>("TeslimAlanPersonelId")
                      .HasColumnType("int");

            b.Property<DateTime?>("TeslimTarihi")
                      .HasColumnType("datetime2");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("datetime2");

            b.HasKey("Id");

            b.HasIndex("TeslimAlanPersonelId");

            b.ToTable("Kargolar");
          });

      modelBuilder.Entity("SantralOpsAPI.Entities.Kisi", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("AdSoyad")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<DateTime>("CreatedDate")
                      .HasColumnType("datetime2");

            b.Property<string>("Notlar")
                      .HasColumnType("nvarchar(max)");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("datetime2");

            b.HasKey("Id");

            b.ToTable("Kisiler");
          });

      modelBuilder.Entity("SantralOpsAPI.Entities.Personel", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("AdSoyad")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<int>("BirimId")
                      .HasColumnType("int");

            b.Property<DateTime>("CreatedDate")
                      .HasColumnType("datetime2");

            b.Property<string>("Dahili")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("Eposta")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<byte[]>("PasswordHash")
                      .IsRequired()
                      .HasColumnType("varbinary(max)");

            b.Property<byte[]>("PasswordSalt")
                      .IsRequired()
                      .HasColumnType("varbinary(max)");

            b.Property<string>("Rol")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("Unvan")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("datetime2");

            b.HasKey("Id");

            b.HasIndex("BirimId");

            b.ToTable("Personeller");
          });

      modelBuilder.Entity("SantralOpsAPI.Entities.Randevu", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<DateTime>("BaslangicZamani")
                      .HasColumnType("datetime2");

            b.Property<DateTime>("BitisZamani")
                      .HasColumnType("datetime2");

            b.Property<DateTime>("CreatedDate")
                      .HasColumnType("datetime2");

            b.Property<int>("KisiId")
                      .HasColumnType("int");

            b.Property<string>("Konu")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<int>("PersonelId")
                      .HasColumnType("int");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("datetime2");

            b.HasKey("Id");

            b.HasIndex("KisiId");

            b.HasIndex("PersonelId");

            b.ToTable("Randevular");
          });

      modelBuilder.Entity("SantralOpsAPI.Entities.TelefonAramaKaydi", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<DateTime>("AramaZamani")
                      .HasColumnType("datetime2");

            b.Property<DateTime>("CreatedDate")
                      .HasColumnType("datetime2");

            b.Property<string>("Notlar")
                      .HasColumnType("nvarchar(max)");

            b.Property<int>("PersonelId")
                      .HasColumnType("int");

            b.Property<int>("TelefonNumarasiId")
                      .HasColumnType("int");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("datetime2");

            b.Property<int>("Yonu")
                      .HasColumnType("int");

            b.HasKey("Id");

            b.HasIndex("PersonelId");

            b.HasIndex("TelefonNumarasiId");

            b.ToTable("TelefonAramaKayitlari");
          });

      modelBuilder.Entity("SantralOpsAPI.Entities.TelefonNumarasi", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<DateTime>("CreatedDate")
                      .HasColumnType("datetime2");

            b.Property<int>("KisiId")
                      .HasColumnType("int");

            b.Property<string>("Numara")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("datetime2");

            b.HasKey("Id");

            b.HasIndex("KisiId");

            b.ToTable("TelefonNumaralari");
          });

      modelBuilder.Entity("SantralOpsAPI.Entities.Ticket", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("Aciklama")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<int?>("AtananPersonelId")
                      .HasColumnType("int");

            b.Property<DateTime>("CreatedDate")
                      .HasColumnType("datetime2");

            b.Property<int>("Durum")
                      .HasColumnType("int");

            b.Property<string>("Konu")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<int>("OlusturanPersonelId")
                      .HasColumnType("int");

            b.Property<int>("Oncelik")
                      .HasColumnType("int");

            b.Property<int>("TalebiYapanKisiId")
                      .HasColumnType("int");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("datetime2");

            b.HasKey("Id");

            b.HasIndex("AtananPersonelId");

            b.HasIndex("OlusturanPersonelId");

            b.HasIndex("TalebiYapanKisiId");

            b.ToTable("Tickets");
          });

      modelBuilder.Entity("SantralOpsAPI.Entities.Kargo", b =>
          {
            b.HasOne("SantralOpsAPI.Entities.Personel", "TeslimAlanPersonel")
                      .WithMany()
                      .HasForeignKey("TeslimAlanPersonelId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("TeslimAlanPersonel");
          });

      modelBuilder.Entity("SantralOpsAPI.Entities.Personel", b =>
          {
            b.HasOne("SantralOpsAPI.Entities.Birim", "Birim")
                      .WithMany("Personeller")
                      .HasForeignKey("BirimId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Birim");
          });

      modelBuilder.Entity("SantralOpsAPI.Entities.Randevu", b =>
          {
            b.HasOne("SantralOpsAPI.Entities.Kisi", "Kisi")
                      .WithMany()
                      .HasForeignKey("KisiId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.HasOne("SantralOpsAPI.Entities.Personel", "Personel")
                      .WithMany()
                      .HasForeignKey("PersonelId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Kisi");

            b.Navigation("Personel");
          });

      modelBuilder.Entity("SantralOpsAPI.Entities.TelefonAramaKaydi", b =>
          {
            b.HasOne("SantralOpsAPI.Entities.Personel", "Personel")
                      .WithMany()
                      .HasForeignKey("PersonelId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.HasOne("SantralOpsAPI.Entities.TelefonNumarasi", "TelefonNumarasi")
                      .WithMany()
                      .HasForeignKey("TelefonNumarasiId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Personel");

            b.Navigation("TelefonNumarasi");
          });

      modelBuilder.Entity("SantralOpsAPI.Entities.TelefonNumarasi", b =>
          {
            b.HasOne("SantralOpsAPI.Entities.Kisi", "Kisi")
                      .WithMany("TelefonNumaralari")
                      .HasForeignKey("KisiId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Kisi");
          });

      modelBuilder.Entity("SantralOpsAPI.Entities.Ticket", b =>
          {
            b.HasOne("SantralOpsAPI.Entities.Personel", "AtananPersonel")
                      .WithMany()
                      .HasForeignKey("AtananPersonelId");

            b.HasOne("SantralOpsAPI.Entities.Personel", "OlusturanPersonel")
                      .WithMany()
                      .HasForeignKey("OlusturanPersonelId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.HasOne("SantralOpsAPI.Entities.Kisi", "TalebiYapanKisi")
                      .WithMany()
                      .HasForeignKey("TalebiYapanKisiId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("AtananPersonel");

            b.Navigation("OlusturanPersonel");

            b.Navigation("TalebiYapanKisi");
          });

      modelBuilder.Entity("SantralOpsAPI.Entities.Birim", b =>
          {
            b.Navigation("Personeller");
          });

      modelBuilder.Entity("SantralOpsAPI.Entities.Kisi", b =>
          {
            b.Navigation("TelefonNumaralari");
          });
#pragma warning restore 612, 618
    }
  }
}
